### ISSUE TITLE
Add option to globally disable shortcut modifications e.g. for the reviewer?

### ISSUE THREAD

**Issue by ijgnd** [Joseph-Y/godmode#2]
I have some add-ons e.g. [right hand reviews / hjkl answer shortcuts / Handy Answer Keys (configurable)](https://ankiweb.net/shared/info/850294128). Your add-on renders mine useless, see [here](https://forums.ankiweb.net/t/right-hand-reviews-hjkl-answer-shortcuts-handy-answer-keys-configurable-official-thread/159/6?u=ijgnd). I think the solution needs to be on your side.

As far as I see modifying the reviewer shortcuts is not a central part of your add-on, it seems to be more of a side-effect. Maybe there could be an additional config key like `"Disable all shortcut modifications for the reviewer": false,` so that the default behavior of your add-on doesn't change but that users who e.g. want to use my add-on could disable your reviewer modifications?

**Comment by Joseph-Y** [comment]
Hey ijgnd, 

From reading the edit to your linked post, I see you understand my rationale. I tried to avoid this problem but the code wouldn't work. 

I think a simpler solution would be for the user to modify the shortcuts to hjkl using the config in my addon. Or if they want the robust features in your add-on, they can delete mine and use yours concurrently with [this one](https://ankiweb.net/shared/info/2105427255). 

I'd reserve the additional config as a last resort, because the more features we add, the more they break with new Anki versions.

Cheers! And by the way, it's awesome that you've contributed 70+ addons.
