### ISSUE TITLE
Cloze Deletions Not Working

### ISSUE THREAD

**Issue by jedward925** [Joseph-Y/godmode#5]
I recently went to study cards created with the Godmode add-on, but all of the close deletion cards do not become close deletion. They stay basic cards with the close deletion formatting. For example, the card appears like this when I study it: "1 + 1 = {{c1::2}}" The "2" part in the close deletion isn't hidden from me.

**Comment by Joseph-Y** [comment]
Hey there. I can think of 2 possible causes:

1. If it worked before and now stopped working, it may be because you updated Anki to a version after 2.1.41. I haven't updated the add-on for those versions. The solution would be to download an older Anki version. But you'd probably have seen an error message on startup if this were the problem, so it's less likely. 

2. Else, double check that your Cloze and Basic cards are named "Cloze" and "Basic" under the note types. If you have a custom-named note types, you can rename them to Basic and Cloze by going to Tools>Manage Note Types>Rename.   

Let me know if that doesn't solve your problem. And sorry for the delay in responding--lot going on right now.
